const data = {
  data: [
    {
      id: '5e7e07e1215e091c132c8f9b',
      name: 'RxSense PBM Admin',
      repos: [
        {
          repoId: 'F6edsBx7',
          repoName: 'rxsense',
          totalViolations: 2,
          totalLineOfCode: 743992,
          codeChurn: -453,
          legacyRefactor: 563,
          technicalDebt: '14 Hours',
          compliance: 9.6,
        },
        {
          repoId: '8mxeZ5hD',
          repoName: 'rxsense.webadmin',
          totalViolations: 2,
          totalLineOfCode: 743992,
          codeChurn: -453,
          legacyRefactor: 563,
          technicalDebt: '14 Hours',
          compliance: 9.6,
        },
      ],
    },
    {
      id: '5e7dbe36215e091c132c8f88',
      name: 'InterMiles',
      repos: [
        {
          repoId: 'IWKidbn0',
          repoName: 'intermiles',
          totalViolations: 2,
          totalLineOfCode: 743992,
          codeChurn: -453,
          legacyRefactor: 563,
          technicalDebt: '14 Hours',
          compliance: 9.6,
        },
        {
          repoId: 'kkc0yPXV',
          repoName: 'IM_Dine',
          totalViolations: 2,
          totalLineOfCode: 743992,
          codeChurn: -453,
          legacyRefactor: 563,
          technicalDebt: '14 Hours',
          compliance: 9.6,
        },
      ],
    },
  ],
}

export default data

export const toolTipData = {
  active: true,
  allowEscapeViewBox: {
    x: false,
    y: false,
  },
  offset: 10,
  viewBox: {
    x: 0,
    y: 0,
    width: 402,
    height: 50,
  },
  coordinate: {
    x: 100.5,
    y: 25,
  },
  cursorStyle: {},
  separator: ' : ',
  wrapperStyle: {},
  contentStyle: {},
  itemStyle: {},
  labelStyle: {},
  cursor: true,
  isAnimationActive: true,
  animationEasing: 'ease',
  animationDuration: 400,
  filterNull: true,
  useTranslate3d: false,
  label: '',
  payload: [
    {
      payload: {
        height: 50,
        width: 201,
        fontSize: 10,
        fill: '#698445',
        stroke: '#ffffff',
        style: { strokeWidth: 1 },
        name: 'Mobile APP backend',
        size: 38096,
        color: '#a3cc6b',
        repoId: '0h0XLdq5',
        repoName: 'Mobile APP backend',
        totalLineOfCode: 38096,
        codeChurn: 0,
        legacyRefactor: 908,
        children: null,
        value: 38096,
        depth: 1,
        index: 0,
        area: 10050,
        x: 0,
        y: 0,
        z: false,
        root: {
          children: [
            {
              name: 'Mobile APP backend',
              size: 38096,
              color: '#a3cc6b',
              repoId: '0h0XLdq5',
              repoName: 'Mobile APP backend',
              totalLineOfCode: 38096,
              codeChurn: 0,
              legacyRefactor: 908,
              children: null,
              value: 38096,
              depth: 1,
              index: 0,
              area: 10050,
              x: 0,
              y: 0,
              width: 201,
              height: 50,
              z: false,
            },
            {
              name: 'Mobile APP backend',
              size: 38096,
              color: '#a3cc6b',
              repoId: '0h0XLdq5',
              repoName: 'Mobile APP backend',
              totalLineOfCode: 38096,
              codeChurn: 0,
              legacyRefactor: 908,
              children: null,
              value: 38096,
              depth: 1,
              index: 1,
              area: 10050,
              x: 201,
              y: 0,
              width: 201,
              height: 50,
              z: false,
            },
            {
              name: 'Other 11 repos',
              size: -1845,
              color: '#a3cc6b',
              repoName: 'Other 11 repos',
              totalViolations: 213,
              totalLineOfCode: -1845,
              codeChurn: -17,
              legacyRefactor: 264,
              children: null,
              value: 0,
              depth: 1,
              index: 2,
              area: 0,
              x: 402,
              y: 0,
              height: 50,
              width: 0,
              z: true,
            },
          ],
          x: 0,
          y: 0,
          width: 402,
          height: 50,
          value: 76192,
          depth: 0,
          index: 0,
        },
      },
      name: '',
      value: 38096,
    },
  ],
}
