const data = {
  data: {
    id: '',
    nestId: '',
    iscProjectId: '5e7dbe36215e091c132c8f88',
    complianceSummary: {
      isPending: true,
      openTickets: 0,
      closedTickets: 0,
      openObservations: 0,
      closedObservations: 0,
    },
    tickets: [],
    observations: [],
  },
}

export default data

export const noModelComplianceData = {
  id: '',
  nestId: '',
  iscProjectId: '5ee31002d48d514e801cb10b',
  complianceSummary: {
    isPending: true,
    openTickets: 0,
    closedTickets: 0,
    openObservations: 0,
    closedObservations: 0,
  },
  tickets: [],
  observations: [],
}

export const modelComplianceData = {
  id: '5efc96ee7c0f2d7b150108cb',
  nestId: '5efc81f87ec3584f8c41e701',
  iscProjectId: '5e7db9f4215e091c132c8f87',
  complianceSummary: {
    isPending: false,
    openTickets: 0,
    closedTickets: 11,
    openObservations: 0,
    closedObservations: 12,
  },
  tickets: [
    {
      status: 'Closed',
      id: 370044,
      number: 'AUD-324',
      name:
        'Training Plan for the team is available however same needs to be prepared in QMS Standard Template',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-324',
      category: 'Minor NC',
      ncRaisedDate: 1563840000000,
      ncDueDate: 1564704000000,
    },
    {
      status: 'Closed',
      id: 370045,
      number: 'AUD-325',
      name:
        'major Risk associated with this Project which needs to be identified and updated in the Risk Register',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-325',
      category: 'Minor NC',
      ncRaisedDate: 1563840000000,
      ncDueDate: 1564704000000,
    },
    {
      status: 'Closed',
      id: 370044,
      number: 'AUD-324',
      name:
        'Training Plan for the team is available however same needs to be prepared in QMS Standard Template',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-324',
      category: 'Minor NC',
      ncRaisedDate: 1563840000000,
      ncDueDate: 1564704000000,
    },
    {
      status: 'Closed',
      id: 370045,
      number: 'AUD-325',
      name:
        'major Risk associated with this Project which needs to be identified and updated in the Risk Register',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-325',
      category: 'Minor NC',
      ncRaisedDate: 1563840000000,
      ncDueDate: 1564704000000,
    },
    {
      status: 'Closed',
      id: 416877,
      number: 'AUD-449',
      name:
        '% Rework is continuously reported 0. Which is incorrect. It should be calculated by logging effort spent on bug fixing from testing and code reviews',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-449',
      category: 'Minor NC',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
    {
      status: 'Closed',
      id: 370044,
      number: 'AUD-324',
      name:
        'Training Plan for the team is available however same needs to be prepared in QMS Standard Template',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-324',
      category: 'Minor NC',
      ncRaisedDate: 1563840000000,
      ncDueDate: 1564704000000,
    },
    {
      status: 'Closed',
      id: 370045,
      number: 'AUD-325',
      name:
        'major Risk associated with this Project which needs to be identified and updated in the Risk Register',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-325',
      category: 'Minor NC',
      ncRaisedDate: 1563840000000,
      ncDueDate: 1564704000000,
    },
    {
      status: 'Closed',
      id: 416877,
      number: 'AUD-449',
      name:
        '% Rework is continuously reported 0. Which is incorrect. It should be calculated by logging effort spent on bug fixing from testing and code reviews',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-449',
      category: 'Minor NC',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
    {
      status: 'Closed',
      id: 370044,
      number: 'AUD-324',
      name:
        'Training Plan for the team is available however same needs to be prepared in QMS Standard Template',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-324',
      category: 'Minor NC',
      ncRaisedDate: 1563840000000,
      ncDueDate: 1564704000000,
    },
    {
      status: 'Closed',
      id: 370045,
      number: 'AUD-325',
      name:
        'major Risk associated with this Project which needs to be identified and updated in the Risk Register',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-325',
      category: 'Minor NC',
      ncRaisedDate: 1563840000000,
      ncDueDate: 1564704000000,
    },
    {
      status: 'Closed',
      id: 416877,
      number: 'AUD-449',
      name:
        '% Rework is continuously reported 0. Which is incorrect. It should be calculated by logging effort spent on bug fixing from testing and code reviews',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-449',
      category: 'Minor NC',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
  ],
  observations: [
    {
      status: 'Closed',
      id: 416872,
      number: 'AUD-444',
      name: 'There was an outstanding amount in invoices of approx 90K pounds',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-444',
      category: 'Observation',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
    {
      status: 'Closed',
      id: 416873,
      number: 'AUD-445',
      name:
        '5.\tIdentification of future training needs of team members was not done as the training register was not evident during the audit',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-445',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
    {
      status: 'Closed',
      id: 416874,
      number: 'AUD-446',
      name:
        'Risk Register - Risk no 1. Description and re assessement columns to be modified and risk to be closed. And add one risk related to Covid 19 and Data security threat at Project level.',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-446',
      category: 'Suggestion',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
    {
      status: 'Closed',
      id: 416875,
      number: 'AUD-447',
      name:
        'Communication Plan on confluence – Needs to be updated to give more clarity on the type of meetings,participants, the written communication,etc as explained during the audit',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-447',
      category: 'Suggestion',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
    {
      status: 'Closed',
      id: 416872,
      number: 'AUD-444',
      name: 'There was an outstanding amount in invoices of approx 90K pounds',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-444',
      category: 'Observation',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
    {
      status: 'Closed',
      id: 416873,
      number: 'AUD-445',
      name:
        '5.\tIdentification of future training needs of team members was not done as the training register was not evident during the audit',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-445',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
    {
      status: 'Closed',
      id: 416874,
      number: 'AUD-446',
      name:
        'Risk Register - Risk no 1. Description and re assessement columns to be modified and risk to be closed. And add one risk related to Covid 19 and Data security threat at Project level.',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-446',
      category: 'Suggestion',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
    {
      status: 'Closed',
      id: 416875,
      number: 'AUD-447',
      name:
        'Communication Plan on confluence – Needs to be updated to give more clarity on the type of meetings',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-447',
      category: 'Suggestion',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
    {
      status: 'Closed',
      id: 416872,
      number: 'AUD-444',
      name: 'There was an outstanding amount in invoices of approx 90K pounds',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-444',
      category: 'Observation',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
    {
      status: 'Closed',
      id: 416873,
      number: 'AUD-445',
      name:
        '5.\tIdentification of future training needs of team members was not done as the training register was not evident during the audit',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-445',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
    {
      status: 'Closed',
      id: 416874,
      number: 'AUD-446',
      name:
        'Risk Register - Risk no 1. Description and re assessement columns to be modified and risk to be closed. And add one risk related to Covid 19 and Data security threat at Project level.',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-446',
      category: 'Suggestion',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
    {
      status: 'Closed',
      id: 416875,
      number: 'AUD-447',
      name:
        'Communication Plan on confluence – Needs to be updated to give more clarity on the type of meetings',
      type: 'Audit Finding',
      url: 'https://jira.infostretch.com/browse/AUD-447',
      category: 'Suggestion',
      ncRaisedDate: 1593388800000,
      ncDueDate: 1595203200000,
    },
  ],
}
