const data = {
  data: [
    {
      id: '5e7e07e1215e091c132c8f9b',
      name: 'RxSense PBM Admin',
      jiraProjectId: 12301,
      sprints: [
        {
          id: 995,
          name: 'Utonagan',
          completedPoints: 2,
          completedCounts: 743,
          squads: 3,
        },
        {
          id: 988,
          name: 'Tosa',
          completedPoints: 102,
          completedCounts: 116,
          squads: 4,
        },
      ],
    },
    {
      id: '5e7dbe36215e091c132c8f88',
      name: 'InterMiles',
      jiraProjectId: 10003,
      sprints: [
        {
          id: 17,
          name: 'Release 3.1.0',
          completedPoints: 8,
          completedCounts: 15,
          squads: 1,
        },
        {
          id: 14,
          name: 'IA Sprint 12 August',
          completedPoints: 126,
          completedCounts: 59,
          squads: 1,
        },
      ],
    },
  ],
}

export default data

export const toolTipData = {
  cursor: false,
  active: true,
  allowEscapeViewBox: {
    x: false,
    y: false,
  },
  offset: 10,
  viewBox: {
    brushBottom: 80,
    top: 10,
    bottom: 80,
    left: 60,
    right: 10,
    width: 570,
    height: 260,
    x: 60,
    y: 10,
  },
  coordinate: {
    x: 117,
    y: 161,
  },
  cursorStyle: {},
  separator: ' : ',
  wrapperStyle: {},
  contentStyle: {},
  itemStyle: {},
  labelStyle: {},
  isAnimationActive: true,
  animationEasing: 'ease',
  animationDuration: 400,
  filterNull: true,
  useTranslate3d: false,
  label: 'Prev Sprint 4',
  payload: [
    {
      stroke: '#a3cc6b',
      fill: '#a3cc6b',
      strokeWidth: '1',
      strokeDasharray: '',
      dataKey: 'InterMiles',
      name: 'InterMiles',
      color: '#a3cc6b',
      value: 16,
      payload: {
        name: 'Prev Sprint 4',
        'RxSense PBM Admin': 253,
        'RxSense PBM AdminData': {
          completed: 253,
          label: 'Story Points',
          name: 'RxSense PBM Admin',
          squads: 4,
        },
        InterMiles: 16,
        InterMilesData: {
          completed: 16,
          label: 'Story Points',
          name: 'Release 3.1.0',
          squads: 1,
        },
      },
    },
    {
      stroke: '#d3b2f8',
      fill: '#d3b2f8',
      strokeWidth: '1',
      strokeDasharray: '',
      dataKey: 'RxSense PBM Admin',
      name: 'RxSense PBM Admin',
      color: '#d3b2f8',
      value: 253,
      payload: {
        name: 'Prev Sprint 4',
        'RxSense PBM Admin': 253,
        'RxSense PBM AdminData': {
          completed: 253,
          label: 'Story Points',
          name: 'RxSense PBM Admin',
          squads: 4,
        },
        InterMiles: 16,
        InterMilesData: {
          completed: 16,
          label: 'Story Points',
          name: 'Release 3.1.0',
          squads: 1,
        },
      },
    },
  ],
  lineIndex: 1,
}

export const toolTipData1 = {
  cursor: false,
  active: true,
  allowEscapeViewBox: {
    x: false,
    y: false,
  },
  offset: 10,
  viewBox: {
    brushBottom: 80,
    top: 10,
    bottom: 80,
    left: 60,
    right: 10,
    width: 570,
    height: 260,
    x: 60,
    y: 10,
  },
  coordinate: {
    x: 117,
    y: 161,
  },
  cursorStyle: {},
  separator: ' : ',
  wrapperStyle: {},
  contentStyle: {},
  itemStyle: {},
  labelStyle: {},
  isAnimationActive: true,
  animationEasing: 'ease',
  animationDuration: 400,
  filterNull: true,
  useTranslate3d: false,
  label: 'Prev Sprint 4',
  payload: [
    {
      stroke: '#a3cc6b',
      fill: '#a3cc6b',
      strokeWidth: '1',
      strokeDasharray: '',
      dataKey: 'InterMiles',
      name: 'InterMiles',
      color: '#a3cc6b',
      value: 16,
      payload: {
        name: 'Prev Sprint 4',
        'RxSense PBM Admin': 253,
        'RxSense PBM AdminData': {
          completed: 253,
          label: 'Story Points',
          name: 'RxSense PBM Admin',
          squads: 4,
        },
        InterMiles: 16,
        InterMilesData: {
          completed: 16,
          label: 'Story Points',
          name: 'Release 3.1.0',
          squads: 1,
        },
      },
    },
  ],
  lineIndex: true,
}
