const data = {
  data: [
    {
      id: '5e7db30b215e091c132c8f83',
      name: 'Alldata Development and QA',
      initials: 'A D A Q',
      category: 'Development & Manual QA',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: 'A',
      jiraProjectId: '10663',
      boards: [
        {
          boardId: '437',
          name: 'ALLDATA Sprint Board',
          sprintId: '2522',
          sprintName: 'Sprint 135',
        },
      ],
      repos: null,
    },
    {
      id: '5e7e2862215e091c132c8f9e',
      name: 'Ally Bank',
      initials: 'A B',
      category: 'Automation QA',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: 'A',
      jiraProjectId: null,
      boards: null,
      repos: null,
    },
    {
      id: '5f4a9183243fe12b4c8277e6',
      name: 'Amplio-Infostretch Development',
      initials: 'A D',
      category: 'Development & Automation QA',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: null,
      jiraProjectId: '10000',
      boards: [
        {
          boardId: '2',
          name: 'Fitness Tracker',
          sprintId: '12',
          sprintName: 'Amplio Mobile Trainer App Sp8',
        },
      ],
      repos: [
        {
          repoId: 'oqZ4vZya',
          repoName: 'Trainer App',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 11337,
        },
        {
          repoId: 'wDyVBg0c',
          repoName: 'Session Services',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 3142,
        },
        {
          repoId: 'U1Slf4jL',
          repoName: 'IAM Services',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 849,
        },
        {
          repoId: '52JskEOX',
          repoName: 'Wearables Services',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 600,
        },
        {
          repoId: 'p4Ym6chb',
          repoName: 'Client Services',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 135,
        },
        {
          repoId: '0cx0vX5n',
          repoName: 'Notification Services',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 6,
        },
        {
          repoId: 'U4NKArZB',
          repoName: 'Trainer Services',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 4,
        },
        {
          repoId: 'e67KK091',
          repoName: 'Gateway Service',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 0,
        },
        {
          repoId: 'FBRPIi9n',
          repoName: 'Wrnch POC',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 0,
        },
        {
          repoId: 'E7uSwnhi',
          repoName: 'Equinox Services',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 0,
        },
      ],
    },
    {
      id: '5e7db800215e091c132c8f85',
      name: 'Aravo Implementation',
      initials: 'A I',
      category: 'Other',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: 'G',
      jiraProjectId: null,
      boards: null,
      repos: null,
    },
    {
      id: '5e7dc595215e091c132c8f8b',
      name: 'Aravo Support Services',
      initials: 'A S S',
      category: 'Support',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: 'G',
      jiraProjectId: null,
      boards: null,
      repos: null,
    },
    {
      id: '5e7dac8e215e091c132c8f7f',
      name: 'AravoQA',
      initials: 'A',
      category: 'Manual & Automation QA',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: 'G',
      jiraProjectId: null,
      boards: null,
      repos: null,
    },
    {
      id: '5e7ded6e215e091c132c8f96',
      name: 'Assistance App L3 Support',
      initials: 'A A L S',
      category: 'Support',
      iconLocation: '',
      overallHealth: 'G',
      jiraProjectId: null,
      boards: null,
      repos: null,
    },
    {
      id: '5ec22809a8875c31ac133611',
      name: 'AutoProtect Data Engineering Services',
      initials: 'A D E S',
      category: 'Devlopment',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: 'A',
      jiraProjectId: null,
      boards: null,
      repos: null,
    },
    {
      id: '5e7db9f4215e091c132c8f87',
      name: 'AutoProtect-.NET development services',
      initials: 'A D S',
      category: 'Development & Automation QA',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: 'G',
      jiraProjectId: null,
      boards: null,
      repos: null,
    },
    {
      id: '5f3fe2e8243fe12b4c8277e2',
      name: 'BioIntellisense Cloud',
      initials: 'B C',
      category: 'Devlopment',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: 'G',
      jiraProjectId: '17038',
      boards: [
        {
          boardId: '282',
          name: 'BioCloud Development Board',
          sprintId: '1383',
          sprintName: 'BioMobile Sprint 20S50',
        },
      ],
      repos: null,
    },
    {
      id: '5f51c5b479f07036c5c1fc5c',
      name: 'BioIntellisense Device Analytics',
      initials: 'B D A',
      category: 'Devlopment',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: null,
      jiraProjectId: '17045',
      boards: [
        {
          boardId: '288',
          name: 'BDA board',
        },
      ],
      repos: null,
    },
    {
      id: '5ec226cea8875c31ac133610',
      name: 'BioIntellisense Mobile App Development',
      initials: 'B M A D',
      category: 'Devlopment',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: 'R',
      jiraProjectId: null,
      boards: null,
      repos: null,
    },
    {
      id: '5fc9f35193072d6d3ae367b4',
      name: 'BioIntellisense Verification & Validation',
      initials: 'B V & V',
      category: 'Devlopment',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: null,
      jiraProjectId: '17048',
      boards: [
        {
          boardId: '293',
          name: 'BIOV board',
          sprintId: '1405',
          sprintName: 'BWS Sprint 8',
        },
      ],
      repos: null,
    },
    {
      id: '5e93fc428b9e081ff0fd4111',
      name: 'Cala Health',
      initials: 'C H',
      category: 'Development & Manual QA',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: 'R',
      jiraProjectId: null,
      boards: null,
      repos: null,
    },
    {
      id: '5ee31002d48d514e801cb10b',
      name: 'Compass',
      initials: 'C',
      category: 'All (Dev & QA & Support)',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: 'R',
      jiraProjectId: '23085',
      boards: [
        {
          boardId: '593',
          name: 'DES Application',
          sprintId: '2529',
          sprintName: 'DES Sprint 22',
        },
        {
          boardId: '583',
          name: 'PSR Compass Utility 2.0',
          sprintId: '2528',
          sprintName: 'CompassUtility Sprint 7',
        },
      ],
      repos: [
        {
          repoId: 'iQ9gR9gG',
          repoName: 'psr-service',
          isScmAvailable: true,
          isSonarAvailable: true,
          totalLineOfCode: 5554,
        },
        {
          repoId: 'LgHq2Npn',
          repoName: 'client-dashboard-service',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 4893,
        },
        {
          repoId: 'JR9BGu4j',
          repoName: 'des-reusable-components',
          isScmAvailable: true,
          isSonarAvailable: true,
          totalLineOfCode: 2355,
        },
        {
          repoId: 'a3yiIBJK',
          repoName: 'des-client',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 614,
        },
        {
          repoId: '93ft6RNl',
          repoName: 'des-common-entities',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 402,
        },
        {
          repoId: 'Eu6HpKsR',
          repoName: 'des-data-utilities',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 355,
        },
        {
          repoId: 'Znj2paDK',
          repoName: 'post-processors',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 215,
        },
        {
          repoId: '0vtgn1Re',
          repoName: 'des-common-utils',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 117,
        },
        {
          repoId: '8okWGGQ9',
          repoName: 'des-pmo',
          isScmAvailable: true,
          isSonarAvailable: true,
          totalLineOfCode: 40,
        },
        {
          repoId: 'KYykN6bG',
          repoName: 'jira-connector',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 34,
        },
        {
          repoId: 'T2aXtihZ',
          repoName: 'des-file-upload',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 21,
        },
        {
          repoId: '5WNaoD6f',
          repoName: 'strategy-service',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 12,
        },
        {
          repoId: 'pje7iKRq',
          repoName: 'des-swagger-configuration',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 4,
        },
        {
          repoId: 'BUYD9TkT',
          repoName: 'sonar-connector',
          isScmAvailable: true,
          isSonarAvailable: true,
          totalLineOfCode: 2,
        },
        {
          repoId: 'ZSG5w52I',
          repoName: 'des-pdo',
          isScmAvailable: true,
          isSonarAvailable: true,
          totalLineOfCode: 0,
        },
        {
          repoId: 'jq9nFPOY',
          repoName: 'des-login',
          isScmAvailable: true,
          isSonarAvailable: true,
          totalLineOfCode: 0,
        },
        {
          repoId: 'tjGV42ad',
          repoName: 'api-gateway',
          isScmAvailable: true,
          isSonarAvailable: true,
          totalLineOfCode: 0,
        },
        {
          repoId: 'xHp14Ztl',
          repoName: 'audit-jira-collector',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 0,
        },
        {
          repoId: 'Vs6FSOqN',
          repoName: 'bitbucket-collector',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 0,
        },
        {
          repoId: 'i762QKE0',
          repoName: 'compass-utility-service',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 0,
        },
        {
          repoId: 'Fs6BrT4R',
          repoName: 'des-config-server',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 0,
        },
        {
          repoId: 'U6qxi7yZ',
          repoName: 'des-exception-handlers',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 0,
        },
        {
          repoId: 'yzDiAx3J',
          repoName: 'github-collector',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 0,
        },
        {
          repoId: '4cxfWRNa',
          repoName: 'nest-data-collector',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 0,
        },
        {
          repoId: '5aAhzn6D',
          repoName: 'psr-connector',
          isScmAvailable: true,
          isSonarAvailable: true,
          totalLineOfCode: 0,
        },
        {
          repoId: 'ZXJe2dTY',
          repoName: 'scm-code-analysis-collector',
          isScmAvailable: true,
          isSonarAvailable: true,
          totalLineOfCode: 0,
        },
        {
          repoId: 'B0hGqK1c',
          repoName: 'user-service',
          isScmAvailable: true,
          isSonarAvailable: true,
          totalLineOfCode: 0,
        },
        {
          repoId: 'IcT1CxZ8',
          repoName: 'des-config-repo',
          isScmAvailable: true,
          isSonarAvailable: false,
          totalLineOfCode: 0,
        },
        {
          repoId: 'Rk2Xv8Wk',
          repoName: 'des-frontend',
          isScmAvailable: false,
          isSonarAvailable: true,
          totalLineOfCode: 0,
        },
        {
          repoId: '0Lbsldsc',
          repoName: 'sonar-service',
          isScmAvailable: false,
          isSonarAvailable: true,
          totalLineOfCode: 0,
        },
      ],
    },
    {
      id: '5f4bca81243fe12b4c8277e7',
      name: 'Corsair MVP',
      initials: 'C M',
      category: 'Development & Manual QA',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: null,
      jiraProjectId: '23863',
      boards: [
        {
          boardId: '572',
          name: 'Corsair Loyalty Portal MVP Implementation (Scrum)',
          sprintId: '2517',
          sprintName: 'Corsair MVP GTM sprint-9',
        },
      ],
      repos: null,
    },
    {
      id: '5e7dcf61215e091c132c8f8c',
      name: 'Crux 24x7x365',
      initials: 'C 2',
      category: 'Support',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: 'A',
      jiraProjectId: null,
      boards: null,
      repos: null,
    },
    {
      id: '5e7db90b215e091c132c8f86',
      name: 'Westhill P2 Dev and QA',
      initials: 'W P D A Q',
      category: 'Development & Manual QA',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: 'A',
      jiraProjectId: null,
      boards: null,
      repos: null,
    },
    {
      id: '5e7dbf53215e091c132c8f89',
      name: 'Whitestuff WebPhase 2',
      initials: 'W W 2',
      category: 'Manual & Automation QA',
      iconLocation: 'http://sampleicon.com/image.png',
      overallHealth: 'G',
      jiraProjectId: null,
      boards: null,
      repos: null,
    },
  ],
}

export default data
