//Overview
export { default as ProjectProgressWidget } from './ProjectProgressWidget/ProjectProgressWidget'
export { default as SprintProgressWidget } from './SprintProgressWidget/SprintProgressWidget'
export { default as ProjectSliderWidget } from './ProjectSliderWidget/ProjectSliderWidget'
export { default as TaskStatusWidget } from './TaskStatusWidget/TaskStatusWidget'
export { default as DefectsCountWidget } from './DefectsCountWidget/DefectsCountWidget'
export { default as LoggedVsAcceptedWidget } from './LoggedVsAcceptedWidget/LoggedVsAcceptedWidget'
export { default as ProjectHealthMetricsWidget } from './ProjectHealthMetricsWidget/ProjectHealthMetricsWidget'
export { default as BlockersWidget } from './BlockersWidget/BlockersWidget'
export { default as MemberStatusWidget } from './MemberStatusWidget/MemberStatusWidget'
export { default as EffortVarianceWidget } from './EffortVarianceWidget/EffortVarianceWidget'
export { default as CalendarViewWidget } from './CalendarViewWidget/CalendarViewWidget'
export { default as ComplianceWidget } from './ComplianceWidget/ComplianceWidget'

//Operational
export { default as StoryPointsDelvsAccWidget } from './StoryPointsDelvsAccWidget/StoryPointsDelvsAccWidget'
export { default as StoryReportsWidget } from './StoryReportsWidget/StoryReportsWidget'
export { default as SprintBurnDownChartWidget } from './SprintBurnDownChartWidget/SprintBurnDownChartWidget'
export { default as TeamVelocityWidget } from './TeamVelocityWidget/TeamVelocityWidget'
export { default as NPSWidget } from './NPSWidget/NPSWidget'
export { default as SayDoRatioWidget } from './SayDoRatioWidget/SayDoRatioWidget'
export { default as SayDoRatioMemberWiseWidget } from './SayDoRatioMemberWiseWidget/SayDoRatioMemberWiseWidget'

//Strategic
export { default as PRsMgmtPieChartWidget } from './PRsMgmtPieChartWidget/PRsMgmtPieChartWidget'
export { default as PRsManagementWidget } from './PRsManagementWidget/PRsManagementWidget'
export { default as SubmitterMetricsWidget } from './SubmitterMetricsWidget/SubmitterMetricsWidget'
export { default as PRmgmtWidget } from './PRmgmtWidget/PRmgmtWidget'
export { default as ViolationTechWiseWidget } from './ViolationTechWiseWidget/ViolationTechWiseWidget'
export { default as RiskWidget } from './RiskWidget/RiskWidget'
export { default as ScoreWidget } from './ScoreWidget/ScoreWidget'
export { default as QualityMetricsWidget } from './QualityMetricsWidget/QualityMetricsWidget'
export { default as ReviewerCollaborationWidget } from './ReviewerCollaborationWidget/ReviewerCollaborationWidget'
export { default as SecurityScoreWidget } from './SecurityScoreWidget/SecurityScoreWidget'
export { default as MemberwiseProductiveCodeWidget } from './MemberwiseProductiveCodeWidget/MemberwiseProductiveCodeWidget'
export { default as MemberwiseActivityMetricsWidget } from './MemberwiseActivityMetricsWidget/MemberwiseActivityMetricsWidget'
export { default as ProjectRatingComplianceWidget } from './ProjectRatingComplianceWidget/ProjectRatingComplianceWidget'
export { default as RepositoryInspectorWidget } from './RepositoryInspectorWidget/RepositoryInspectorWidget'

//Client
export { default as StoryPointsDelTrendWidget } from './StoryPointsDelTrendWidget/StoryPointsDelTrendWidget'
export { default as StoryPointsDefectRatioWidget } from './StoryPointsDefectRatioWidget/StoryPointsDefectRatioWidget/StoryPointsDefectRatioWidget'
export { default as StoryPointsDefectRatioGraphWidget } from './StoryPointsDefectRatioWidget/StoryPointsDefectRatioGraphWidget/StoryPointsDefectRatioGraphWidget'
export { default as StoryPointsDelTrendProjectWidget } from './StoryPointsDelTrendWidget/StoryPointsDelTrendProjectWidget'
export { default as StoryPointsDelTrendProjectSprintWidget } from './StoryPointsDelTrendWidget/StoryPointsDelTrendProjectSprintWidget'
export { default as VelocityTrendsWidget } from './VelocityTrendsWidget/VelocityTrendsWidget'
export { default as VelocityTrendsProjectWidget } from './VelocityTrendsWidget/VelocityTrendsProjectWidget'
export { default as ProjectCompletionTrendsWidget } from './ProjectCompletionTrendsWidget/ProjectCompletionTrendsWidget'
export { default as DefectTrendsWidget } from './DefectTrendsWidget/DefectTrendsWidget'
export { default as ProductHealthOverviewSunBurst } from './ProductHealthOverviewSunBurst/ProductHealthOverviewSunBurst'
export { default as CodeMetricsClientWidget } from './CodeMetricsClientWidget/CodeMetricsClientWidget'
export { default as CodeHealthSnapshotWidget } from './CodeHealthSnapshotWidget/CodeHealthSnapshotWidget'
export { default as CodeViolationClientWidget } from './CodeViolationClientWidget/CodeViolationClientWidget'
export { default as CodeScoreClientWidget } from './CodeScoreClientWidget/CodeScoreClientWidget'
export { default as CodeTechnicalDebtClientWidget } from './CodeTechnicalDebtClientWidget/CodeTechnicalDebtClientWidget'
export { default as CodeSmellAndIssuesClientWidget } from './CodeSmellAndIssuesClientWidget/CodeSmellAndIssuesClientWidget'
export { default as SecurityComplianceScoreWidget } from './SecurityComplianceScoreWidget/SecurityComplianceScoreWidget'
export { default as DefectAgeingWidget } from './DefectAgeingWidget/DefectAgeingWidget'
export { default as DefectAgeingProjectWiseWidget } from './DefectAgeingProjectWiseWidget/DefectAgeingProjectWiseWidget'
export { default as DefectTrendTypeWidget } from './DefectTrendTypeWidget/DefectTrendTypeWidget'
export { default as DefectTrendSeverityWidget } from './DefectTrendSeverityWidget/DefectTrendSeverityWidget'
export { default as DefectTrendsAcceptanceWidget } from './DefectTrendsAcceptanceWidget/DefectTrendsAcceptanceWidget'
export { default as DefectTrendTypeProjectWiseWidget } from './DefectTrendTypeProjectWiseWidget/DefectTrendTypeProjectWiseWidget'
export { default as DefectTrendSeverityProjectWiseWidget } from './DefectTrendSeverityProjectWiseWidget/DefectTrendSeverityProjectWiseWidget'
export { default as DefectTrendAcceptanceProjectWiseWidget } from './DefectTrendAcceptanceProjectWiseWidget/DefectTrendAcceptanceProjectWiseWidget'
