const data = {
  data: {
    overall: {
      lineOfCode: 1953706,
      codeChurn: 100,
      legacyRefactor: 1042,
      addedLineOfCode: 388,
      removedLineOfCode: 44,
      addedLineOfCodeTotal: 5823836,
      removedLineOfCodeTotal: 3870130,
    },
    members: [
      {
        name: 'Lakshmi Ravoori',
        lineOfCode: 344,
        codeChurn: 55,
        legacyRefactor: 0,
        addedLineOfCode: 388,
        removedLineOfCode: 44,
        addedLineOfCodeTillDate: 100,
        removedLineOfCodeTillDate: 44,
      },
      {
        name: 'abhid30080',
        lineOfCode: 24,
        lineOfCodeInSprint: 95,
        codeChurn: 55,
        legacyRefactor: 0,
        addedLineOfCode: 167,
        removedLineOfCode: 143,
        addedLineOfCodeTillDate: 100,
        removedLineOfCodeTillDate: 44,
      },
    ],
    average: {
      lineOfCode: 6182.61,
      codeChurn: 55,
      legacyRefactor: 0,
      addedLineOfCode: 388,
      removedLineOfCode: 44,
      addedLineOfCodeTillDate: 100,
      removedLineOfCodeTillDate: 44,
    },
  },
}
export default data

export const toolTipData = {
  cursor: false,
  active: true,
  allowEscapeViewBox: {
    x: false,
    y: false,
  },
  offset: 10,
  viewBox: {
    brushBottom: 125,
    top: 5,
    bottom: 125,
    left: 65,
    right: 5,
    width: 453,
    height: 170,
    x: 65,
    y: 5,
  },
  coordinate: {
    x: 223.54999999999998,
    y: 104,
  },
  cursorStyle: {},
  separator: ' : ',
  wrapperStyle: {},
  contentStyle: {},
  itemStyle: {},
  labelStyle: {},
  isAnimationActive: true,
  animationEasing: 'ease',
  animationDuration: 400,
  filterNull: true,
  useTranslate3d: false,
  label: 'Sunny Vaghadia',
  payload: [
    {
      fill: '#979797',
      strokeDasharray: '',
      dataKey: 'Legacy Refactor',
      name: 'Legacy Refactor',
      color: '#979797',
      value: 0,
      payload: {
        'Code Churn': 0,
        'Legacy Refactor': 0,
        'Added Lines Of Code': 3376,
        'Removed Lines Of Code': 3376,
        'Added Line Of Code Till Date': 36615,
        'Removed Line Of Code Till Date': 17191,
        name: 'Sunny Vaghadia',
        displayTimeDuration: 'Last 3 Months',
      },
    },
    {
      fill: '#24ff00',
      strokeDasharray: '',
      dataKey: 'Code Churn',
      name: 'Code Churn',
      color: '#24ff00',
      value: 0,
      payload: {
        'Code Churn': 0,
        'Legacy Refactor': 0,
        'Added Lines Of Code': 3376,
        'Removed Lines Of Code': 3376,
        'Added Line Of Code Till Date': 36615,
        'Removed Line Of Code Till Date': 17191,
        name: 'Sunny Vaghadia',
        displayTimeDuration: 'Last 3 Months',
      },
    },
    {
      fill: '#ffc145',
      strokeDasharray: '',
      dataKey: 'Removed Lines Of Code',
      name: 'Removed Lines Of Code',
      color: '#ffc145',
      value: 3376,
      payload: {
        'Code Churn': 0,
        'Legacy Refactor': 0,
        'Added Lines Of Code': 3376,
        'Removed Lines Of Code': 3376,
        'Added Line Of Code Till Date': 36615,
        'Removed Line Of Code Till Date': 17191,
        name: 'Sunny Vaghadia',
        displayTimeDuration: 'Last 3 Months',
      },
    },
    {
      fill: '#1a91eb',
      strokeDasharray: '',
      dataKey: 'Added Lines Of Code',
      name: 'Added Lines Of Code',
      color: '#1a91eb',
      value: 3376,
      payload: {
        'Code Churn': 0,
        'Legacy Refactor': 0,
        'Added Lines Of Code': 3376,
        'Removed Lines Of Code': 3376,
        'Added Line Of Code Till Date': 36615,
        'Removed Line Of Code Till Date': 17191,
        name: 'Sunny Vaghadia',
        displayTimeDuration: 'Last 3 Months',
      },
    },
  ],
}
