const data = {
  data: {
    id: '5fa3b04a28bf219417878bb6',
    name: 'InterMiles',
    jiraProjectId: 10003,
    range: [
      { value: '0-3', critical: 1, blocker: 0, major: 2, minor: 0, unattended: 3 },
      { value: '3-5', critical: 0, blocker: 0, major: 0, minor: 0, unattended: 0 },
      { value: '6-10', critical: 4, blocker: 0, major: 3, minor: 0, unattended: 6 },
      { value: '11-20', critical: 1, blocker: 1, major: 4, minor: 0, unattended: 11 },
      { value: '21-30', critical: 0, blocker: 0, major: 1, minor: 0, unattended: 3 },
      { value: '31-40', critical: 0, blocker: 0, major: 1, minor: 0, unattended: 6 },
      { value: '41-50', critical: 1, blocker: 1, major: 0, minor: 0, unattended: 5 },
      { value: '51-75', critical: 1, blocker: 1, major: 13, minor: 0, unattended: 16 },
      { value: '75-100', critical: 1, blocker: 2, major: 4, minor: 0, unattended: 21 },
      { value: '>100', critical: 25, blocker: 10, major: 63, minor: 0, unattended: 79 },
    ],
  },
}

export default data

export const toolTipData = {
  cursor: false,
  active: true,
  allowEscapeViewBox: {
    x: false,
    y: false,
  },
  offset: 10,
  viewBox: {
    brushBottom: 80,
    top: 10,
    bottom: 80,
    left: 50,
    right: 10,
    width: 464,
    height: 210,
    x: 50,
    y: 10,
  },
  coordinate: {
    x: 127.33333333333333,
    y: 211,
  },
  cursorStyle: {},
  separator: ' : ',
  wrapperStyle: {},
  contentStyle: {},
  itemStyle: {},
  labelStyle: {},
  isAnimationActive: true,
  animationEasing: 'ease',
  animationDuration: 400,
  filterNull: true,
  useTranslate3d: false,
  label: 'Nov-20',
  payload: [
    {
      fill: 'transparent',
      stroke: '#952323',
      strokeDasharray: '3 3',
      dataKey: 'Backlog.Blocker',
      name: 'Backlog.Blocker',
      color: 'transparent',
      value: 23,
      payload: {
        name: 'Nov-20',
        Backlog: {
          Blocker: 23,
          Critical: 115,
          Major: 232,
          Minor: 113,
        },
        Planned: {
          Blocker: 21,
          Critical: 97,
          Major: 257,
          Minor: 46,
        },
      },
    },
    {
      fill: 'transparent',
      stroke: '#5c4893',
      strokeDasharray: '3 3',
      dataKey: 'Backlog.Critical',
      name: 'Backlog.Critical',
      color: 'transparent',
      value: 115,
      payload: {
        name: 'Nov-20',
        Backlog: {
          Blocker: 23,
          Critical: 115,
          Major: 232,
          Minor: 113,
        },
        Planned: {
          Blocker: 21,
          Critical: 97,
          Major: 257,
          Minor: 46,
        },
      },
    },
    {
      fill: 'transparent',
      stroke: '#1d7097',
      strokeDasharray: '3 3',
      dataKey: 'Backlog.Major',
      name: 'Backlog.Major',
      color: 'transparent',
      value: 232,
      payload: {
        name: 'Nov-20',
        Backlog: {
          Blocker: 23,
          Critical: 115,
          Major: 232,
          Minor: 113,
        },
        Planned: {
          Blocker: 21,
          Critical: 97,
          Major: 257,
          Minor: 46,
        },
      },
    },
    {
      fill: 'transparent',
      stroke: '#399a65',
      strokeDasharray: '3 3',
      dataKey: 'Backlog.Minor',
      name: 'Backlog.Minor',
      color: 'transparent',
      value: 113,
      payload: {
        name: 'Nov-20',
        Backlog: {
          Blocker: 23,
          Critical: 115,
          Major: 232,
          Minor: 113,
        },
        Planned: {
          Blocker: 21,
          Critical: 97,
          Major: 257,
          Minor: 46,
        },
      },
    },
    {
      fill: '#952323',
      strokeDasharray: '',
      dataKey: 'Planned.Blocker',
      name: 'Planned.Blocker',
      color: '#952323',
      value: 21,
      payload: {
        name: 'Nov-20',
        Backlog: {
          Blocker: 23,
          Critical: 115,
          Major: 232,
          Minor: 113,
        },
        Planned: {
          Blocker: 21,
          Critical: 97,
          Major: 257,
          Minor: 46,
        },
      },
    },
    {
      fill: '#5c4893',
      strokeDasharray: '',
      dataKey: 'Planned.Critical',
      name: 'Planned.Critical',
      color: '#5c4893',
      value: 97,
      payload: {
        name: 'Nov-20',
        Backlog: {
          Blocker: 23,
          Critical: 115,
          Major: 232,
          Minor: 113,
        },
        Planned: {
          Blocker: 21,
          Critical: 97,
          Major: 257,
          Minor: 46,
        },
      },
    },
    {
      fill: '#1d7097',
      strokeDasharray: '',
      dataKey: 'Planned.Major',
      name: 'Planned.Major',
      color: '#1d7097',
      value: 257,
      payload: {
        name: 'Nov-20',
        Backlog: {
          Blocker: 23,
          Critical: 115,
          Major: 232,
          Minor: 113,
        },
        Planned: {
          Blocker: 21,
          Critical: 97,
          Major: 257,
          Minor: 46,
        },
      },
    },
    {
      fill: '#399a65',
      strokeDasharray: '',
      dataKey: 'Planned.Minor',
      name: 'Planned.Minor',
      color: '#399a65',
      value: 46,
      payload: {
        name: 'Nov-20',
        Backlog: {
          Blocker: 23,
          Critical: 115,
          Major: 232,
          Minor: 113,
        },
        Planned: {
          Blocker: 21,
          Critical: 97,
          Major: 257,
          Minor: 46,
        },
      },
    },
  ],
}
