const data = {
  data: {
    projectId: 12301,
    projectName: 'RxSense PBM Admin',
    sprintData: [
      {
        sprintId: 975,
        name: 'Rottweiler',
        dayWiseData: [
          {
            day: 1,
            openTillNowPoints: 141,
            completedPoints: 107,
            reopenPoints: 0,
            newlyAddedPoints: 0,
            openTillNowCount: 92,
            completedCount: 74,
            reopenCount: 0,
            newlyAddedCount: 0,
          },
          {
            day: 2,
            openTillNowPoints: 137,
            completedPoints: 113,
            reopenPoints: 0,
            newlyAddedPoints: 0,
            openTillNowCount: 92,
            completedCount: 74,
            reopenCount: 0,
            newlyAddedCount: 0,
          },
          {
            day: 3,
            openTillNowPoints: 134,
            completedPoints: 117,
            reopenPoints: 0,
            newlyAddedPoints: 0,
            openTillNowCount: 92,
            completedCount: 74,
            reopenCount: 0,
            newlyAddedCount: 0,
          },
        ],
      },
      {
        sprintId: 966,
        name: 'Pug',
        dayWiseData: [
          {
            day: 1,
            openTillNowPoints: 141,
            completedPoints: 107,
            reopenPoints: 0,
            newlyAddedPoints: 0,
            openTillNowCount: 92,
            completedCount: 74,
            reopenCount: 0,
            newlyAddedCount: 0,
          },
          {
            day: 2,
            openTillNowPoints: 137,
            completedPoints: 113,
            reopenPoints: 0,
            newlyAddedPoints: 0,
            openTillNowCount: 92,
            completedCount: 74,
            reopenCount: 0,
            newlyAddedCount: 0,
          },
          {
            day: 3,
            openTillNowPoints: 134,
            completedPoints: 117,
            reopenPoints: 0,
            newlyAddedPoints: 0,
            openTillNowCount: 92,
            completedCount: 74,
            reopenCount: 0,
            newlyAddedCount: 0,
          },
        ],
      },
      {
        sprintId: 957,
        name: 'Otterhound',
        dayWiseData: [
          {
            day: 1,
            openTillNowPoints: 141,
            completedPoints: 107,
            reopenPoints: 0,
            newlyAddedPoints: 0,
            openTillNowCount: 92,
            completedCount: 74,
            reopenCount: 0,
            newlyAddedCount: 0,
          },
          {
            day: 2,
            openTillNowPoints: 137,
            completedPoints: 113,
            reopenPoints: 0,
            newlyAddedPoints: 0,
            openTillNowCount: 92,
            completedCount: 74,
            reopenCount: 0,
            newlyAddedCount: 0,
          },
          {
            day: 3,
            openTillNowPoints: 134,
            completedPoints: 117,
            reopenPoints: 0,
            newlyAddedPoints: 0,
            openTillNowCount: 92,
            completedCount: 74,
            reopenCount: 0,
            newlyAddedCount: 0,
          },
        ],
      },
    ],
  },
}

export default data
