const data = {
  data: [
    {
      projectId: 12301,
      projectName: 'RxSense PBM Admin',
      sprintId: 957,
      name: 'Pug',
      dayWiseData: [
        {
          day: 1,
          openTillNowPoints: 141,
          completedPoints: 107,
          reopenPoints: 0,
          newlyAddedPoints: 0,
          idealCompletedPoints: 120,
          openTillNowCount: 92,
          completedCount: 74,
          reopenCount: 0,
          newlyAddedCount: 0,
          idealCompletedCount: 75,
        },
        {
          day: 2,
          openTillNowPoints: 137,
          completedPoints: 113,
          reopenPoints: 0,
          newlyAddedPoints: 0,
          idealCompletedPoints: 120,
          openTillNowCount: 92,
          completedCount: 74,
          reopenCount: 0,
          newlyAddedCount: 0,
          idealCompletedCount: 75,
        },
        {
          day: 3,
          openTillNowPoints: 134,
          completedPoints: 117,
          reopenPoints: 0,
          newlyAddedPoints: 0,
          idealCompletedPoints: 120,
          openTillNowCount: 92,
          completedCount: 74,
          reopenCount: 0,
          newlyAddedCount: 0,
          idealCompletedCount: 75,
        },
      ],
    },
    {
      projectId: 12302,
      projectName: 'RxSense-DWH',
      sprintId: 957,
      name: 'Pug',
      dayWiseData: [
        {
          day: 1,
          openTillNowPoints: 141,
          completedPoints: 107,
          reopenPoints: 0,
          newlyAddedPoints: 0,
          idealCompletedPoints: 120,
          openTillNowCount: 92,
          completedCount: 74,
          reopenCount: 0,
          newlyAddedCount: 0,
          idealCompletedCount: 75,
        },
        {
          day: 2,
          openTillNowPoints: 137,
          completedPoints: 113,
          reopenPoints: 0,
          newlyAddedPoints: 0,
          idealCompletedPoints: 120,
          openTillNowCount: 92,
          completedCount: 74,
          reopenCount: 0,
          newlyAddedCount: 0,
          idealCompletedCount: 75,
        },
        {
          day: 3,
          openTillNowPoints: 134,
          completedPoints: 117,
          reopenPoints: 0,
          newlyAddedPoints: 0,
          idealCompletedPoints: 120,
          openTillNowCount: 92,
          completedCount: 74,
          reopenCount: 0,
          newlyAddedCount: 0,
          idealCompletedCount: 75,
        },
      ],
    },
  ],
}

export default data

export const toolTipData = {
  cursor: false,
  active: true,
  allowEscapeViewBox: {
    x: false,
    y: false,
  },
  offset: 10,
  viewBox: {
    brushBottom: 80,
    top: 10,
    bottom: 80,
    left: 60,
    right: 10,
    width: 570,
    height: 260,
    x: 60,
    y: 10,
  },
  coordinate: {
    x: 324.6428571428571,
    y: 262,
  },
  cursorStyle: {},
  separator: ' : ',
  wrapperStyle: {},
  contentStyle: {},
  itemStyle: {},
  labelStyle: {},
  isAnimationActive: true,
  animationEasing: 'ease',
  animationDuration: 400,
  filterNull: true,
  useTranslate3d: false,
  label: 'Day 7',
  payload: [
    {
      stroke: '#d3b2f8',
      fill: '#d3b2f8',
      strokeWidth: '1',
      strokeDasharray: '',
      dataKey: 'RxSense PBM Admin',
      name: 'RxSense PBM Admin',
      color: '#d3b2f8',
      value: 197,
      payload: {
        name: 'Day 7',
        'RxSense PBM Admin': 197,
        completed: 50,
        openTillNow: 197,
        reopen: 5,
        newlyAdded: 2,
        'RxSense PBM AdminData': {
          name: 'Day 7',
          'RxSense PBM Admin': 197,
          completed: 50,
          openTillNow: 197,
          reopen: 5,
          newlyAdded: 2,
        },
      },
    },
    {
      stroke: '#d3b2f8',
      fill: '#d3b2f8',
      strokeWidth: '1',
      strokeDasharray: '',
      dataKey: 'RxSense PBM Admin',
      name: 'RxSense PBM Admin',
      color: '#d3b2f8',
      value: 197,
      payload: {
        name: 'Day 7',
        'RxSense PBM Admin': 197,
        completed: 50,
        openTillNow: 197,
        reopen: 5,
        newlyAdded: 2,
        'RxSense PBM AdminData': {
          name: 'Day 7',
          'RxSense PBM Admin': 197,
          completed: 50,
          openTillNow: 197,
          reopen: 5,
          newlyAdded: 2,
        },
      },
    },
  ],
  lineIndex: 1,
}

export const toolTipDataIndexFalse = {
  cursor: false,
  active: true,
  allowEscapeViewBox: {
    x: false,
    y: false,
  },
  offset: 10,
  viewBox: {
    brushBottom: 80,
    top: 10,
    bottom: 80,
    left: 60,
    right: 10,
    width: 570,
    height: 260,
    x: 60,
    y: 10,
  },
  coordinate: {
    x: 324.6428571428571,
    y: 262,
  },
  cursorStyle: {},
  separator: ' : ',
  wrapperStyle: {},
  contentStyle: {},
  itemStyle: {},
  labelStyle: {},
  isAnimationActive: true,
  animationEasing: 'ease',
  animationDuration: 400,
  filterNull: true,
  useTranslate3d: false,
  label: 'Day 7',
  payload: [
    {
      stroke: '#d3b2f8',
      fill: '#d3b2f8',
      strokeWidth: '1',
      strokeDasharray: '',
      dataKey: 'RxSense PBM Admin',
      name: 'RxSense PBM Admin',
      color: '#d3b2f8',
      value: 197,
      payload: {
        name: 'Day 7',
        'RxSense PBM Admin': 197,
        completed: 50,
        openTillNow: 197,
        reopen: 5,
        newlyAdded: 2,
        'RxSense PBM AdminData': {
          name: 'Day 7',
          'RxSense PBM Admin': 197,
          completed: 50,
          openTillNow: 197,
          reopen: 5,
          newlyAdded: 2,
        },
      },
    },
  ],
  lineIndex: false,
}
