const data = {
  config: {
    tooltip: true,
    toolTipType: 'color',
    legend: true,
    legendIconType: 'circle',
    legendMargin: {
      top: 20,
      right: 0,
      left: 0,
      bottom: 0,
    },
    height: 350,
    margin: {
      top: 10,
      right: 0,
      left: 0,
      bottom: 0,
    },
    x: {
      tick: { fill: '#01ffff' },
      stroke: '#01ffff',
      axisLine: true,
      tickLine: true,
      allowDataOverflow: true,
      dataKey: 'name',
      dx: 0,
      angle: -90,
      height: 80,
    },
    y: {
      tick: { fill: '#01ffff' },
      stroke: '#01ffff',
      axisLine: true,
      tickLine: true,
      label: 'Story Point',
      dy: 160,
      angle: -90,
      fontSize: 13,
      fill: '#01ffff',
    },
    cartesianGrid: {
      horizontal: true,
      vertical: false,
      stroke: '#01ffff',
      fillOpacity: 0.5,
      fill: true,
    },
    line: [
      {
        key: 'Remaining Tasks',
        type: 'monotone',
        dot: false,
        stroke: '#f8ff73',
        strokeWidth: '1',
      },
      {
        key: 'Ideal Completed',
        type: 'monotone',
        dot: false,
        stroke: '#00d2ff',
        strokeWidth: '1',
      },
      {
        key: 'Remaining Efforts',
        type: 'monotone',
        dot: true,
        stroke: '#24ff00',
        strokeWidth: '1',
      },
    ],
    bar: [
      {
        key: 'Completed Tasks',
        type: 'linear',
        yAxisId: 'left',
        barSize: 7,
        stroke: '#7849ea',
      },
    ],
  },
  data: [
    {
      'Completed Tasks': 3,
      'Ideal Completed': 36,
      'Remaining Efforts': 49,
      'Remaining Tasks': 29,
      name: 'Day 1',
    },
    {
      'Completed Tasks': 6,
      'Ideal Completed': 32,
      'Remaining Efforts': 46,
      'Remaining Tasks': 25,
      name: 'Day 2',
    },
    {
      'Completed Tasks': 7,
      'Ideal Completed': 28,
      'Remaining Efforts': 46,
      'Remaining Tasks': 24,
      name: 'Day 3',
    },
    {
      'Completed Tasks': 8,
      'Ideal Completed': 25,
      'Remaining Efforts': 46,
      'Remaining Tasks': 23,
      name: 'Day 4',
    },
    {
      'Completed Tasks': 8,
      'Ideal Completed': 25,
      'Remaining Efforts': 46,
      'Remaining Tasks': 23,
      name: 'Day 5',
    },
    {
      'Completed Tasks': 8,
      'Ideal Completed': 25,
      'Remaining Efforts': 46,
      'Remaining Tasks': 23,
      name: 'Day 6',
    },
    {
      'Completed Tasks': 9,
      'Ideal Completed': 21,
      'Remaining Efforts': 46,
      'Remaining Tasks': 22,
      name: 'Day 7',
    },
    {
      'Completed Tasks': 11,
      'Ideal Completed': 18,
      'Remaining Efforts': 46,
      'Remaining Tasks': 20,
      name: 'Day 8',
    },
    {
      'Completed Tasks': 14,
      'Ideal Completed': 14,
      'Remaining Efforts': 46,
      'Remaining Tasks': 17,
      name: 'Day 9',
    },
    {
      'Completed Tasks': 14,
      'Ideal Completed': 10,
      'Remaining Efforts': 46,
      'Remaining Tasks': 17,
      name: 'Day 10',
    },
    {
      'Completed Tasks': 21,
      'Ideal Completed': 7,
      'Remaining Efforts': 15,
      'Remaining Tasks': 10,
      name: 'Day 11',
    },
    {
      'Completed Tasks': 20,
      'Ideal Completed': 7,
      'Remaining Efforts': 20,
      'Remaining Tasks': 11,
      name: 'Day 12',
    },
    {
      'Completed Tasks': 20,
      'Ideal Completed': 7,
      'Remaining Efforts': 20,
      'Remaining Tasks': 11,
      name: 'Day 13',
    },
    {
      'Completed Tasks': 20,
      'Ideal Completed': 3,
      'Remaining Efforts': 20,
      'Remaining Tasks': 11,
      name: 'Day 14',
    },
  ],
}

export default data

export const mockConfigData = {
  config: {
    topLabel: true,
    color: true,
    tooltip: true,
    toolTipType: 'color',
    legend: true,
    legendIconType: 'circle',
    legendMargin: {
      top: 20,
      right: 0,
      left: 0,
      bottom: 0,
    },
    margin: {
      top: 10,
      right: 0,
      left: 0,
      bottom: 0,
    },
    x: {
      tick: { fill: '#01ffff' },
      stroke: '#01ffff',
      axisLine: true,
      tickLine: true,
      allowDataOverflow: true,
      dataKey: 'name',
      dx: 0,
      angle: -90,
      height: 80,
    },
    y: {
      tick: { fill: '#01ffff' },
      stroke: '#01ffff',
      axisLine: true,
      tickLine: true,
      label: 'Story Point',
      angle: -90,
      fontSize: 13,
      fill: '#01ffff',
      hide: true,
    },
    cartesianGrid: {
      horizontal: true,
      vertical: false,
      stroke: '#01ffff',
      fillOpacity: 0.5,
      fill: true,
    },
    line: [
      {
        key: 'Remaining Tasks',
        type: 'monotone',
        dot: false,
        stroke: '#f8ff73',
        strokeWidth: '1',
      },
      {
        key: 'Ideal Completed',
        type: 'monotone',
        dot: false,
        stroke: '#00d2ff',
        strokeWidth: '1',
      },
      {
        key: 'Remaining Efforts',
        type: 'monotone',
        dot: true,
        stroke: '#24ff00',
        strokeWidth: '1',
      },
    ],
    bar: [
      {
        key: 'Completed Tasks',
        type: 'linear',
        yAxisId: 'left',
        barSize: 7,
        stroke: '#7849ea',
      },
    ],
  },
  data: [
    {
      'Completed Tasks': 3,
      'Ideal Completed': 36,
      'Remaining Efforts': 49,
      'Remaining Tasks': 29,
      name: 'Day 1',
    },
    {
      'Completed Tasks': 6,
      'Ideal Completed': 32,
      'Remaining Efforts': 46,
      'Remaining Tasks': 25,
      name: 'Day 2',
    },
    {
      'Completed Tasks': 7,
      'Ideal Completed': 28,
      'Remaining Efforts': 46,
      'Remaining Tasks': 24,
      name: 'Day 3',
    },
    {
      'Completed Tasks': 8,
      'Ideal Completed': 25,
      'Remaining Efforts': 46,
      'Remaining Tasks': 23,
      name: 'Day 4',
    },
    {
      'Completed Tasks': 8,
      'Ideal Completed': 25,
      'Remaining Efforts': 46,
      'Remaining Tasks': 23,
      name: 'Day 5',
    },
    {
      'Completed Tasks': 8,
      'Ideal Completed': 25,
      'Remaining Efforts': 46,
      'Remaining Tasks': 23,
      name: 'Day 6',
    },
    {
      'Completed Tasks': 9,
      'Ideal Completed': 21,
      'Remaining Efforts': 46,
      'Remaining Tasks': 22,
      name: 'Day 7',
    },
    {
      'Completed Tasks': 11,
      'Ideal Completed': 18,
      'Remaining Efforts': 46,
      'Remaining Tasks': 20,
      name: 'Day 8',
    },
    {
      'Completed Tasks': 14,
      'Ideal Completed': 14,
      'Remaining Efforts': 46,
      'Remaining Tasks': 17,
      name: 'Day 9',
    },
    {
      'Completed Tasks': 14,
      'Ideal Completed': 10,
      'Remaining Efforts': 46,
      'Remaining Tasks': 17,
      name: 'Day 10',
    },
    {
      'Completed Tasks': 21,
      'Ideal Completed': 7,
      'Remaining Efforts': 15,
      'Remaining Tasks': 10,
      name: 'Day 11',
    },
    {
      'Completed Tasks': 20,
      'Ideal Completed': 7,
      'Remaining Efforts': 20,
      'Remaining Tasks': 11,
      name: 'Day 12',
    },
    {
      'Completed Tasks': 20,
      'Ideal Completed': 7,
      'Remaining Efforts': 20,
      'Remaining Tasks': 11,
      name: 'Day 13',
    },
    {
      'Completed Tasks': 20,
      'Ideal Completed': 3,
      'Remaining Efforts': 20,
      'Remaining Tasks': 11,
      name: 'Day 14',
    },
  ],
}
