const data = {
  data: [
    {
      repoId: '497zR4Wi',
      repoName: 'Rx2',
      monthData: [
        {
          month: 'Jul-2020',
          security: 0.56,
          complexity: 9061.0,
          issues: 4080.0,
          reliability: 0.11,
          size: 33792.0,
          coverage: 0.0,
          duplication: 2.38,
          maintainability: 24.77,
          totalDays: 25.44,
        },
        {
          month: 'Aug-2020',
          security: 0.56,
          complexity: 9061.0,
          issues: 4080.0,
          reliability: 0.11,
          size: 33792.0,
          coverage: 0.0,
          duplication: 2.38,
          maintainability: 24.77,
          totalDays: 25.44,
        },
        {
          month: 'Sep-2020',
          security: 0.56,
          complexity: 9061.0,
          issues: 4080.0,
          reliability: 0.11,
          size: 33792.0,
          coverage: 0.0,
          duplication: 2.38,
          maintainability: 24.77,
          totalDays: 25.44,
        },
      ],
    },
  ],
}

export default data

export const toolTipData = {
  cursor: false,
  active: true,
  allowEscapeViewBox: {
    x: false,
    y: false,
  },
  offset: 10,
  viewBox: {
    brushBottom: 80,
    top: 10,
    bottom: 80,
    left: 40,
    right: 10,
    width: 277,
    height: 160,
    x: 40,
    y: 10,
  },
  coordinate: {
    x: 86.16666666666666,
    y: 165,
  },
  cursorStyle: {},
  separator: ' : ',
  wrapperStyle: {},
  contentStyle: {},
  itemStyle: {},
  labelStyle: {},
  isAnimationActive: true,
  animationEasing: 'ease',
  animationDuration: 400,
  filterNull: true,
  useTranslate3d: false,
  label: 'Jan-2021',
  payload: [
    {
      stroke: '#2bb834',
      fill: '#2bb834',
      strokeWidth: '1',
      strokeDasharray: '',
      dataKey: 'ProductiveCodeLine',
      name: 'ProductiveCodeLine',
      color: '#2bb834',
      value: 1.4,
      payload: {
        name: 'Jan-2021',
        ProductiveCode: 1.4,
        ProductiveCodeLine: 1.4,
        totalDays: 1.4,
        maintainability: 1.4,
        reliability: 0,
        security: 0,
      },
    },
    {
      fill: '#2bb834',
      strokeDasharray: '',
      dataKey: 'ProductiveCode',
      name: 'ProductiveCode',
      color: '#2bb834',
      value: 1.4,
      payload: {
        name: 'Jan-2021',
        ProductiveCode: 1.4,
        ProductiveCodeLine: 1.4,
        totalDays: 1.4,
        maintainability: 1.4,
        reliability: 0,
        security: 0,
      },
    },
  ],
}
